// flow-typed signature: 9065f12a056426db31a32ac8e910ac54
// flow-typed version: <<STUB>>/grid-styled_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grid-styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grid-styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grid-styled/dist/Grid' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Grid' {
  declare module.exports: any;
}

declare module 'grid-styled/test/Grid' {
  declare module.exports: any;
}

declare module 'grid-styled/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grid-styled/dist/Grid.js' {
  declare module.exports: $Exports<'grid-styled/dist/Grid'>;
}
declare module 'grid-styled/src/Grid.js' {
  declare module.exports: $Exports<'grid-styled/src/Grid'>;
}
declare module 'grid-styled/test/Grid.js' {
  declare module.exports: $Exports<'grid-styled/test/Grid'>;
}
declare module 'grid-styled/webpack.config.js' {
  declare module.exports: $Exports<'grid-styled/webpack.config'>;
}
