// flow-typed signature: 0549c03788eb3912cd223a8038f43c03
// flow-typed version: <<STUB>>/html-pdf_v^2.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-pdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-pdf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-pdf/bin/index' {
  declare module.exports: any;
}

declare module 'html-pdf/lib/index' {
  declare module.exports: any;
}

declare module 'html-pdf/lib/pdf' {
  declare module.exports: any;
}

declare module 'html-pdf/lib/scripts/pdf_a4_portrait' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-pdf/bin/index.js' {
  declare module.exports: $Exports<'html-pdf/bin/index'>;
}
declare module 'html-pdf/lib/index.js' {
  declare module.exports: $Exports<'html-pdf/lib/index'>;
}
declare module 'html-pdf/lib/pdf.js' {
  declare module.exports: $Exports<'html-pdf/lib/pdf'>;
}
declare module 'html-pdf/lib/scripts/pdf_a4_portrait.js' {
  declare module.exports: $Exports<'html-pdf/lib/scripts/pdf_a4_portrait'>;
}
