// flow-typed signature: c526568832044471de9f5c37c6740bf8
// flow-typed version: <<STUB>>/meta-marked_v^0.4.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meta-marked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type Meta = {
  [key: string]: any,
};

declare module 'meta-marked' {
  declare function exports(content: string) : {
    +meta: Object,
    +html: string,
    +markdown: string
  }
// @flow

}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'meta-marked/lib/meta-marked' {
  declare module.exports: any;
}

declare module 'meta-marked/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'meta-marked/lib/meta-marked.js' {
  declare module.exports: $Exports<'meta-marked/lib/meta-marked'>;
}
declare module 'meta-marked/test/test.js' {
  declare module.exports: $Exports<'meta-marked/test/test'>;
}
