// flow-typed signature: 01809e8b8eefd76937691b14ea329606
// flow-typed version: <<STUB>>/purecss_v^0.6.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purecss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'purecss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'purecss/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'purecss/index' {
  declare module.exports: $Exports<'purecss'>;
}
declare module 'purecss/index.js' {
  declare module.exports: $Exports<'purecss'>;
}
declare module 'purecss/test/index.js' {
  declare module.exports: $Exports<'purecss/test/index'>;
}
